### PR TITLE
Automate the model choices/map for future additions + New seg backbone (hrnetv2)

### PR DESCRIPTION
**Pull request by timothylimyl**
Models are all found at `network/modeling.py` , we might else well just automate the process of retrieving the models that we have written there for the usage in `main.py` and `predict.py`. 

By calling/leveraging `network.modeling.__dict__`, we can retrieve the names of the model and functions in a more automatic fashion. We do not need to manually add in the model names in both the argument parser section and model map.

The sole changes to the code are only to argument parser model choices and the deletion of `model_map`, done in both `main.py` and `predict.py`

**Side note: I am very sorry about the changes made by the linting (adding spaces everywhere), please ignore them, let me know if it is not acceptable.**

### CODE REVIEW

**Comment by timothylimyl** [comment]
Hi @VainF ,

I did not realised that pushing new commits after raising the PR will add onto the current PR.

After commit no.5 onwards, it is all commits to integrating the new backbone HRNetV2.  I am still in the midst of training the deeplabv3plus_hrnetv2_32 network for cityscapes, will post the pretrained weights once it is done.

**Comment by VainF** [comment]
Get it! Thanks for your great work. Please let me know if this PR is ready.

**Comment by timothylimyl** [comment]
Hi @VainF , mainly just waiting for the training to finish so that you will at least have a pretrained model weight to run with. Code wise, it is already usable for training.

I think will take ~12 more hours of training to be done. I will share the backbone weight and seg model weight here once it is done.

**Comment by timothylimyl** [comment]
Done. DeepLabV3Plus-HRNetv2-32 for cityscapes. Validation Stats:
```
Overall Acc: 0.961567
Mean Acc: 0.850273
FreqW Acc: 0.928497
Mean IoU: 0.774661
```

Training call:
```
CUDA_VISIBLE_DEVICES=0 python main.py --model deeplabv3plus_hrnetv2_32 --dataset cityscapes --enable_vis \

--vis_port 8097 --lr 0.03 --crop_size 768 --batch_size 2 --val_batch_size 2 \

--data_root ./datasets/data/cityscapes --val_interval 10000 --total_itrs 200000
```
Train with relative fewer iterations in terms of batch size. From looking at the graph at visdom, I think it has not converged yet **but I cannot seem to continue training as there is an issue with PolyLR for `--continue-training`. Reference issue: #59**

Once resolved, I believe it can be potentially better if we go for more iterations updates.


Pretrained weights can be found:

HRNetV2-32 Backbone: 
https://drive.google.com/file/d/1NxCK7Zgn5PmeS7W1jYLt5J9E0RRZ2oyF/view?usp=sharing

 DeepLabV3Plus-HRNetv2-32 for cityscapes:  https://drive.google.com/file/d/1U2yGxQszJN9fTeNJG3skqL2hREQZTm3Y/view?usp=sharing


Run predictions:
```
python predict.py --input datasets/data/cityscapes/leftImg8bit/train/bremen  --model deeplabv3plus_hrnetv2_32 \

 --ckpt checkpoints/best_deeplabv3plus_hrnetv2_32_cityscapes_os4.pth \

 --save_val_results_to test_results --dataset cityscapes
```

Note: Output stride does not matter for hrnetv2, it is standardized at 4. One of the main ideas of the backbone is to retain high resolutions.

**Comment by timothylimyl** [comment]
Hi @VainF , is it good to merge?

**Comment by VainF** [comment]
@timothylimyl A little busy in the past few days and sorry for the late reply.  This PR looks great, so let's merge it to the main branch. Thanks!

**Pull request merged**
